config/routes.rb
Rails.application.routes.draw do


  devise_for :users	
  resources :users,only:[:show, :index, :edit, :update]
  # root to: 'home#top'
  get 'home/about' => 'home#about'

  resources :users, only: [:index, :show] do
    get :favorites, on: :member
  end

  resources :books do
    resource :favorites, only: [:create, :destroy]
  end
  root'books#index'

  root 'users#index'
  resources :users, only: [:show, :index] do
  	resource :relationships, only: [:create, :destroy]
  	get :follows, on: :member
  	get :followers, on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :favorites, dependent: :destroy
	def favorited_by? user
		# binding.pry
		favorites.where(user_id: user.id).exists?		
	end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :book
	belongs_to :user

	validates :user_id, presence: true
	validates :book_id, presence: true
	validates :user_id, uniqueness: {scope: :book_id}
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :following, class_name: User
	belongs_to :followed, class_name: User

	validates :followed_id, presence: true
	validates :following_id, presence: true
	validates :following_id, uniqueness: { scope: :followed_id }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
	       :recoverable, :rememberable, :trackable, :validatable
	has_many :books
	mount_uploader :image, ImageUploader
	
	has_many :active_relationships, class_name: 'Relationship', foreign_key: :following_id
	has_many :passive_relationships, class_name: 'Relationship', foreign_key: :followed_id
	has_many :followings, through: :active_relationships, source: :followed
	has_many :followers, through: :passive_relationships, source: :following
	def followed_by?(user)
		passive_relationships.find_by(following_id: user.id).present?
	end

	has_many :favorites, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	# before_action :authenticate_user!
  	before_action :configure_permitted_parameters, if: :devise_controller?
  
	def after_sign_in_path_for(resource)
		user_path(current_user)	
	end

  protected

    def configure_permitted_parameters
      # sign_upのときに、nameをストロングパラメータに追加する
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :image])
      # account_updateのときに、nameをストロングパラメータに追加する
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email, :image])
    end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!
	before_action :correct_user, only:[:edit, :update]

	def create
		@book = Book.new(book_params)
		@book.user_id = current_user.id
		@book.save
		redirect_to books_path
	end

	def index
		@books = Book.all.order(created_at: :desc)
	end

	def show
		@book = Book.find(params[:id])
	end

	def edit
		@book = Book.find(params[:id])
	end

	def destroy
		@book = Book.find(params[:book_id])
		@book.destroy
		redirect_to books_path
	end

	def update
		@book = Book.find(params[:book_id])
		unless @book.user_id.present?
			@book.user_id = current_user.id
		end
		@book.update(book_params)
		redirect_to books_path(@book.id)
	end

private
	def book_params
		params.require(:book).permit(:title, :user_id, :opinion)
	end

  def correct_user
    book = Book.find(params[:book_id])
    if current_user.id != book.user_id
      redirect_to root_path
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	before_action :authenticate_user!

  def create
  	# binding.pry
  	@book = Book.find(params[:book_id])
  	favorite = current_user.favorites.build(book: @book)
    favorite.save
  	# if @favorite.save
  	# 	redirect_to root_path, notice: "お気に入りに登録しました"
  	# else
  	# 	redirect_to books_path, alert: "この投稿はお気に入りに登録できません"
  	# end	
  end

  def destroy
    # binding.pry
    @book = Book.find(params[:book_id])
  	favorite = current_user.favorites.find_by!(book_id: @book)
  	favorite.destroy
  	# redirect_to books_path, notice: "お気に入りを解除しました"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def top		
	end
	def about
		
	end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
	before_action :authenticate_user!
	def create
		follow = current_user.active_relationships.build(followed_id: params[:user_id])
		follow.save
		# 	redirect_to root_path, notice: "フォローしました"
		# else
		# 	redirect_to root_path, alart: "フォローできません"
		# end
	end

	def destroy
		follow = current_user.active_relationships.find_by!(followed_id: params[:user_id])
		follow.destroy
		# 	redirect_to root_path, notice: "フォロー解除しました"
		# end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!

  def index
  	@users = User.all
  end

  def show
    # @users = User.all
  	@user = User.find(params[:id])
  	# @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(users_params)
    redirect_to user_path(@user.id)
  end

  def follows
    @user = User.find(params[:id]) 
    @follows = @user.followings
  end

  def followers
    @user = User.find(params[:id])     
    @followers = @user.followers
  end

  def favorites
    @user = User.find(params[:id])
  end

private
  def users_params
    params.require(:user).permit(:name, :image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="body">
<div class="container box">
	<h1>Editing Book</h1>
	  <div class="col-xs-3"></div>

	  <div class="col-xs-9">
		<%= form_for(@book) do |f| %>
			<%= f.label :title, class: "col-xs-12" %>
			<%= f.text_field :title, class: "col-xs-12" %>
			<%= f.label :opinion, class: "col-xs-12" %>
			<%= f.text_field :opinion, class: "col-xs-12" %>
			<%= f.submit 'Update Book', class: "btn btn-primary col-xs-12"%>
		<% end %>
		<%= link_to 'Show', book_path(@book.id) %>|<%= link_to 'Back', books_path %>
	  </div>
</div>
</div>

app/views/books/index.html.erb
<div class="container box">
        
        <p id="notice"></p>
      
      	<div class="row">
      		<div class="col-xs-3">
      			<%= render 'shared/userinfo', user: current_user %>
				<%= render 'shared/newbook', book: Book.new %>
      		</div>
				


			<div class="col-xs-9">
			    <h2>Books</h2>
			    	<table class="table table-hover table-inverse">
						<thead>
						<tr> 
				          <th></th>
				          <th>Title</th>
				          <th>Opinion</th>
				          <th colspan="3"></th>
			          	</tr>
			      		</thead>

					      <tbody>
					      	<% @books.each do |book| %>
					      	<tr>
							    <% if book.user.image? %>
							        <td><%= image_tag book.user.image.url, style:"width:40px; height:40px;" %></td>  
							    <% else %>
							        <td><%= image_tag 'no_image.jpg', style:"width:40px; height:40px;"  %></td>
							    <% end %>
							    <td><%= link_to book.title, book_path(book.id) %></td>
							 	<td><%= book.opinion %></td>
								<td id="favorite-btn-<%=book.id%>"><%= render 'favorites/favorite', book: book %></td>
						    	<th colspan="3"></th>
						    </tr>
						    <% end %>
					      </tbody>
			    	</table>
			</div>
		</div>
</div>

app/views/books/show.html.erb
<div class="container box">
        
        <p id="notice"></p>
      
      	<div class="row">
      		<div class="col-xs-3">
      			<%= render 'shared/userinfo', user: current_user %>
				<%= render 'shared/newbook', book: Book.new %>
      		</div>
				
			<div class="col-xs-9">
			    <h1>Book detail</h1>
			    	<!-- <table class="table table-hover table-inverse">
					      <tbody>
					      	<tr>
					      		<th></th>
							    <td><%#= book.title %></td>
							 	<td><%#= book.opinion %></td>
							 	<td><%#= link_to 'Edit', edit_book_path %></td>
							 	<td><%#= link_to 'Destroy', book_path, method: :delete %></td>
						    	<th colspan="3"></th>
						    </tr>
					      </tbody>
			    	</table> -->
			    <h3>タイトル</h3>
			    <h2><%= @book.title %></h2>
			    <hr>
			    <h3>説明</h3>
			    <p><%= @book.opinion %></p>
			    <hr>
			    <h4>投稿者</h4>
			    <% if @book.user.image? %>
				    <%= image_tag @book.user.image.url %>	
				    <% else %>
				    <%= image_tag 'no_image.jpg' %>
			    <% end %>
			    <h4 id="favorite-btn-<%=@book.id%>"><%= render 'favorites/favorite', book: @book %></h4>
			    <div>
			    	<% if @book.user.present? %>
			    		<%= link_to @book.user.name, user_path(@book.user_id) %>
			    	<% else %>
			    		ユーザーはいません
			    	<% end %>
			    	<% if current_user.id == @book.user_id %>
						<%= link_to 'Edit', edit_book_path(@book.id) %>
						<%= link_to 'Destroy', book_path(@book.id), method: :delete, data: { confirm: "本当に削除しますか？" } %>
					<% end %>
			    </div>
			</div>
		</div>
</div>

app/views/favorites/_favorite.html.erb
<% if book.favorited_by? current_user %>
	<%= link_to "❤︎ いいね!", book_favorites_path(book), method: :delete, remote: true %>
		 <%#= books.favorites.count %>
<% else %>
	<%= link_to "♡ いいね!", book_favorites_path(book), method: :post, remote: true  %>
		 <%#= books.favorites.count %>
<% end %>

app/views/favorites/create.html.erb
<h1>Favorites#create</h1>
<p>Find me in app/views/favorites/create.html.erb</p>

app/views/favorites/create.js.erb
$('#favorite-btn-<%= @book.id %>').html("<%= j(render 'favorites/favorite', book: @book) %>")

app/views/favorites/destroy.html.erb
<h1>Favorites#destroy</h1>
<p>Find me in app/views/favorites/destroy.html.erb</p>

app/views/favorites/destroy.js.erb
$('#favorite-btn-<%= @book.id %>').html("<%= j(render 'favorites/favorite', book: @book) %>")

app/views/home/about.html.erb
<div class="container box">
        
        <p id="notice"></p>
      
      	<h1>Welcome to <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>!</h1>


      </div>

app/views/home/top.html.erb
<div class="container box">
        
        <p id="notice"></p>
      
      	<div class="row">
  <div class="top-message col-md-offset-3 col-md-6">
    <h1>welcome to <span class="glyphicon glyphicon-book"><strong>Bookers</strong>  !!</span></h1>
          <p>In  <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>, </p>
          <p>you can share and exchange  your opinions , inpressions , and emotions</p>
          <p> about varioius books!</p>

    <div class="btn-wrapper">
      <div class="row">
         <p><%= link_to 'Log in', new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1" %></p>
      </div>
      <div class="row">
        <p><%= link_to 'Sign Up', new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1" %></p>
      </div>
    </div>
            
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

 <header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav class="nav navbar-nav navbar-left">
      <span class="glyphicon glyphicon-book">Bookers</span>
    </nav>
    <nav>
      <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
      	<li><%= link_to ' Home', user_path(current_user), class:"glyphicon glyphicon-home" %></li>
      	<li><%= link_to 'Users', users_path, class:"glyphicon glyphicon-home" %></li>
      	<li><%= link_to 'Books', books_path, class:"glyphicon glyphicon-home" %></li>
      	<li><%= link_to ' logout', destroy_user_session_path, method: :delete, class:"glyphicon glyphicon-link" %></li>
      <% else %>
      	<li><%= link_to ' Home', root_path, class:"glyphicon glyphicon-home" %></li>
      	<li><%= link_to ' About', home_about_path, class:"glyphicon glyphicon-link" %></li>
      	<li><%= link_to ' sign up', new_user_registration_path, class:"glyphicon glyphicon-edit" %></li>
      	<li><%= link_to ' login', new_user_session_path, class:"glyphicon glyphicon-log-in" %></li>
<!--           <li><a class="glyphicon glyphicon-home" href="/"> Home</a></li>
          <li><a class="glyphicon glyphicon-link" href="/home/about"> About</a></li>
          <li><a class="glyphicon glyphicon-edit" href="/users/sign_up"> sign up</a></li>
          <li><a class="glyphicon glyphicon-log-in" href="/users/sign_in"> login</a></li> -->
      <% end %>
      </ul>
    </nav>
  </div>
</header>

    <%= yield %>
  </body>
</html>

app/views/relationships/create.js.erb
$('#relationships-btn-<%= @user.id %>').html("<%= j(render 'shared/relationship', user: @user) %>")

app/views/relationships/destroy.js.erb
$('#relationships-btn-<%= @user.id %>').html("<%= j(render 'shared/relationship', user: @user) %>")

app/views/relationships/followers.html.erb
<div class="container box">
        followers.html.erb
        <p id="notice"></p>
      
      	<div class="row">
      	<div class="col-xs-3">
			<%= render 'shared/userinfo', user: current_user %>
			<%= render 'shared/newbook', book: Book.new %>
		</div>
			<div class="col-xs-9">
			    <h2>Users</h2>
			    	<table class="table table-hover table-inverse">
						<thead>
						<tr> 
				          <th></th>
				          <th>image</th>
				          <th>name</th>
				          <th colspan="3"></th>
			          	</tr>
			      		</thead>

					      <tbody>
					      <% @followers.each do |user| %>
						  	<tr>
						      	<th></th>
						      	<% if user.image? %>
							     	<td><%= image_tag user.image.url %></td>	
								    <% else %>
								    <td><%= image_tag 'no_image.jpg' %></td>
								<% end %>		      
					   			<td><%= user.name %></td>
								<td><%= link_to 'show', user_path(user.id) %></td>
							   <th colspan="3"></th>
							   <% if current_user != user %>
								   	<td><% if user.followed_by?(current_user) %>
								   		<%= link_to "follow解除", user_relationships_path(user), method: :delete %>
								   	<% else %>
								   	<%= link_to "followする", user_relationships_path(user), method: :post %></td>	
								   	<% end %>
							   	<% end %>
							</tr>
						  <% end %>
					      </tbody>
			    	</table>
			</div>
		</div>
</div>

app/views/shared/_newbook.html.erb
<div class="col-xs-12">
    <h2>New book</h2>

<%= form_for(book) do |f| %>
	<div class="field row">
	  <%= f.label :title, class: "col-xs-12" %>
	  <%= f.text_field :title, class: "col-xs-12" %>
	</div>
	<div class="field row">
	  <%= f.label :opinion,  class: "col-xs-12" %>
	  <%= f.text_area :opinion, class: "col-xs-12" %>
	</div>
  <%= f.submit 'Create Book', class: "btn btn-primary col-xs-12" %>
<% end %>

</div>

app/views/shared/_relationship.html.erb
<% if user.followed_by?(current_user) %>
	<%= link_to "follow解除", user_relationships_path(user), method: :delete, remote: true %>
<% else %>
	<%= link_to "followする", user_relationships_path(user), method: :post, remote: true %>	
<% end %>

app/views/shared/_userinfo.html.erb
<div class="col-xs-12">
    <h2>User info</h2>
      <% if user.image? %>
          <td><%= image_tag user.image.url %></td>  
          <% else %>
          <td><%= image_tag 'no_image.jpg' %></td>
      <% end %>
      <table class="table">
      <tbody><tr></tr> 
      <tr>
    	  <th>name</th>
    	  <th><%= user.name %></th>
      </tr>
      <tr>
    	  <th>introduction</th>
    	  <th><%= user.introduction %></th>
      </tr>
    </tbody></table>
    <% if user_signed_in? %>
      <div class="row">
        <%= link_to follows_user_path(user), class: "btn btn-default col-xs-6" do %>
          <strong><%= user.followings.count %></strong> followings
        <% end %>
        <%= link_to followers_user_path(user), class: "btn btn-default col-xs-6" do %>
          <strong><%= user.followers.count %></strong> followers
        <% end %>
        <%= link_to user_path(user), class: "btn btn-default col-xs-6" do %>
          <strong><%= user.books.count %></strong>books
        <% end %>
        <%= link_to favorites_user_path(user), class: "btn btn-default col-xs-6" do %>
          <strong><%= user.favorites.count %></strong>favorites
        <% end %>
        <%= link_to edit_user_path(user.id), class: "btn btn-default col-xs-12" do %>
          <i class="glyphicon glyphicon-wrench"></i>
        <% end %>
      </div>
    <% end %>
  </div>

app/views/users/edit.html.erb
<div class="container box">
	<h2>User info</h2>

	<%= form_for(@user) do |f| %>
		<div class="field">
			<%= f.label :name %>
			<%= f.text_field :name %>
		</div>
		<div class="field">
			<%= f.label :image %>
			<%= f.file_field :image %>
		</div>
		<div class="field">
			<%= f.label :introduction %>
			<%= f.text_field :introduction %>
		</div>
            <%= f.submit %>
	<% end %>
</div>

app/views/users/favorites.html.erb
<div class="container box">
        
        <p id="notice"></p>
      
      	<div class="row">
      		<div class="col-xs-3">
      			<%= render 'shared/userinfo', user: current_user %>
				<%= render 'shared/newbook', book: Book.new %>
      		</div>
				
			<div class="col-xs-9">
				<h2>Favorites Books</h2>
			    	<table class="table table-hover table-inverse">
						<thead>
						<tr> 
				          <th></th>
				          <th>Title</th>
				          <th>Opinion</th>
				          <th colspan="3"></th>
			          	</tr>
			      		</thead>

					    <tbody>
						    <% @user.books.each do |book| %>
						    	<tr>					    		
							      	<% if book.user.image? %>
								      	<td><%= image_tag book.user.image.url, style:"width:40px; height:40px;" %></td>
								      	<% else %>
								      	<td><%= image_tag 'no_image.jpg', style:"width:40px; height:40px;" %></td>
							      	<% end %>
								    <td><%= link_to book.title, book_path(book.id) %></td>
									<td><%= book.opinion %></td>
									<td id="favorite-btn-<%=book.id%>"><%= render 'favorites/favorite', book: book %></td>
						    		<th colspan="3"></th>
						    	</tr>
						    <% end %>    
					    </tbody>
			    	</table>
				</div>
		</div>
</div>

app/views/users/followers.html.erb
<div class="container box">

        <p id="notice"></p>
      
      	<div class="row">
      	<div class="col-xs-3">
			<%= render 'shared/userinfo', user: current_user %>
			<%= render 'shared/newbook', book: Book.new %>
		</div>
			<div class="col-xs-9">
			    <h2>Users</h2>
			    	<table class="table table-hover table-inverse">
						<thead>
						<tr> 
				          <th></th>
				          <th>image</th>
				          <th>name</th>
				          <th colspan="3"></th>
			          	</tr>
			      		</thead>

					      <tbody>
					      <% @followers.each do |user| %>
						  	<tr>
						      	<th></th>
						      	<% if user.image? %>
							     	<td><%= image_tag user.image.url, style:"width:40px; height:40px;" %></td>	
								    <% else %>
								    <td><%= image_tag 'no_image.jpg', style:"width:40px; height:40px;" %></td>
								<% end %>		      
					   			<td><%= user.name %></td>
								<td><%= link_to 'show', user_path(user.id) %></td>
							   <th colspan="3"></th>
							   <% if current_user != user %>
									<td id="relationships-btn-<%= user.id %>"><%= render 'shared/relationship', user: user %></td>
							   	<% end %>
							</tr>
						  <% end %>
					      </tbody>
			    	</table>
			</div>
		</div>
</div>

app/views/users/follows.html.erb
<div class="container box">

        <p id="notice"></p>
      
      	<div class="row">
      	<div class="col-xs-3">
			<%= render 'shared/userinfo', user: current_user %>
			<%= render 'shared/newbook', book: Book.new %>
		</div>
			<div class="col-xs-9">
			    <h2>Users</h2>
			    	<table class="table table-hover table-inverse">
						<thead>
						<tr> 
				          <th></th>
				          <th>image</th>
				          <th>name</th>
				          <th colspan="3"></th>
			          	</tr>
			      		</thead>

					      <tbody>
					      <% @follows.each do |user| %>
						  	<tr>
						      	<th></th>
						      	<% if user.image? %>
							     	<td><%= image_tag user.image.url, style:"width:40px; height:40px;" %></td>	
								    <% else %>
								    <td><%= image_tag 'no_image.jpg', style:"width:40px; height:40px;" %></td>
								<% end %>		      
					   			<td><%= user.name %></td>
								<td><%= link_to 'show', user_path(user.id) %></td>
							   <th colspan="3"></th>
							   <% if current_user != user %>
									<td id="relationships-btn-<%= user.id %>"><%= render 'shared/relationship', user: user %></td>
							   	<% end %>
							</tr>
						  <% end %>
					      </tbody>
			    	</table>
			</div>
		</div>
</div>

app/views/users/index.html.erb
<div class="container box">
        
        <p id="notice"></p>
      
      	<div class="row">
      	<div class="col-xs-3">
			<%= render 'shared/userinfo', user: current_user %>
			<%= render 'shared/newbook', book: Book.new %>
		</div>
			<div class="col-xs-9">
			    <h2>Users</h2>
			    	<table class="table table-hover table-inverse">
						<thead>
						<tr> 
				          <th></th>
				          <th>image</th>
				          <th>name</th>
				          <th colspan="3"></th>
			          	</tr>
			      		</thead>

					      <tbody>
					      <% @users.each do |user| %>
						  	<tr>
						      	<th></th>
						      	<% if user.image? %>
							     	<td><%= image_tag user.image.url, style:"width:40px; height:40px;" %></td>	
								    <% else %>
								    <td><%= image_tag 'no_image.jpg', style:"width:40px; height:40px;" %></td>
								<% end %>		      
					   			<td><%= user.name %></td>
								<td><%= link_to 'show', user_path(user.id) %></td>
							   <th colspan="3"></th>
							   <% if current_user != user %>
								<td id="relationships-btn-<%= user.id %>"><%= render 'shared/relationship', user: user %></td>
							   <% end %>
							</tr>
						  <% end %>
					      </tbody>
			    	</table>
			</div>
		</div>
</div>

app/views/users/show.html.erb
<div class="container box">
        
        <p id="notice"></p>
      
      	<div class="row">
      		<div class="col-xs-3">
      			<%= render 'shared/userinfo', user: current_user %>
				<%= render 'shared/newbook', book: Book.new %>
      		</div>
				
			<div class="col-xs-9">
			    <h2>Books</h2>
			    	<table class="table table-hover table-inverse">
						<thead>
						<tr> 
				          <th></th>
				          <th>Title</th>
				          <th>Opinion</th>
				          <th colspan="3"></th>
			          	</tr>
			      		</thead>

					      <tbody>
					      	<% @user.books.each do |book| %>
					      	<tr>
						      	<% if book.user.image? %>
						      		<td><%= image_tag book.user.image.url, style:"width:40px; height:40px;" %></td>
						      	<% else %>
						      		<td class="userimage"><%= image_tag 'no_image.jpg', style:"width:40px; height:40px;" %></td>
						      	<% end %>
							    <td><%= link_to book.title, book_path(book.id) %></td>
								<td><%= book.opinion %></td>
								<td id="favorite-btn-<%=book.id%>"><%= render 'favorites/favorite', book: book %></td>
						    	<th colspan="3"></th>
						    </tr>
						    <% end %>
					      </tbody>
			    	</table>
			</div>
		</div>
</div>